//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Web.Mvc;

namespace Sgtcc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aluno : Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aluno()
        {
            this.Tccs = new HashSet<Tcc>();
        }      

        [Required]
        [Display(Name = "Matrícula")]
        //[Index(IsUnique = true)]
        [RegularExpression("^[0-9]{12}$", ErrorMessage = "Matrícula must have 12 digits.")]
        public string matricula { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tcc> Tccs { get; set; }
    }
}
