//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgtcc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Arquivo
    {
        public int Id { get; set; }
        public string nome { get; set; }

        public string extensao { get; set; }
        public string caminho { get; set; }
    
        public virtual Tcc Tcc { get; set; }

        public string LoginErrorMessage { get; set; }
    }
}
