//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Sgtcc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CronogramaAgendamento
    {
        public int Id { get; set; }

        [Required]
        [Display(Name = "Prazo Final")]
        public string prazoInicial { get; set; }


        [Required]
        [Display(Name = "Prazo Final")]
        public string prazoFinal { get; set; }
    }
}
