//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sgtcc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<Aluno> Alunos { get; set; }
        public virtual DbSet<Professor> Professores { get; set; }
        public virtual DbSet<Tcc> Tccs { get; set; }
        public virtual DbSet<Tcc2> Tccs2 { get; set; }
        public virtual DbSet<Banca> Bancas { get; set; }
        public virtual DbSet<MembrosBanca> MembrosBancas { get; set; }
        public virtual DbSet<Arquivo> Arquivoes { get; set; }
        public virtual DbSet<CronogramaArquivo> CronogramaArquivoes { get; set; }
        public virtual DbSet<CronogramaAgendamento> CronogramaAgendamentoes { get; set; }
    }
}
