//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Sgtcc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tcc2 : Tcc
    {
        [DataType(DataType.Date)]
        [Display(Name = "Data")]
        public string data { get; set; }
        [Display(Name = "Local")]
        public string local { get; set; }
        public virtual Banca Banca { get; set; }

        [Display(Name = "Professores Avaliadores")]
        public string professoresBanca { get; set; }
    }
}
