//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Sgtcc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tcc2 : Tcc
    {
        public string data { get; set; }
        public string local { get; set; }
        [Display(Name = "Orientador")]
        [DataType(DataType.Text)]
        public string Orientador { get; set; }
        public virtual Banca Banca { get; set; }
    }
}
